### ISSUE TITLE
"Attempt to push null on operand stack!" error after upgrading to 1.9.23

### ISSUE THREAD

**Issue by tmortagne** [eclipse-aspectj/aspectj#327]
I just upgraded from 1.9.22.1 to 1.9.23, and I end up with the following error when using it through the [aspectj maven plugin](https://github.com/mojohaus/aspectj-maven-plugin) 1.15.0:

```
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.15.0:compile (backward-compatibility-aspects) on project xwiki-platform-legacy-oldcore: AJC compiler errors:
[ERROR] error at
[ERROR] (no source information available)
[ERROR] /media/DATA/xwiki/sources/xwiki-platform/xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/doc/XWikiDocumentCompatibilityAspect.aj:0::0 Internal compiler error: java.lang.AssertionError: Attempt to push null on operand stack! at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:58)
[ERROR] abort ABORT -- (AssertionError) Attempt to push null on operand stack!
[ERROR] Attempt to push null on operand stack!
[ERROR] java.lang.AssertionError: Attempt to push null on operand stack!
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:58)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:84)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload_0(CodeStream.java:334)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6322)
[ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.InterTypeFieldDeclaration.generateClassWriteBody(InterTypeFieldDeclaration.java:480)
[ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.InterTypeFieldDeclaration.generateDispatchMethod(InterTypeFieldDeclaration.java:391)
[ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.InterTypeFieldDeclaration.generateDispatchMethods(InterTypeFieldDeclaration.java:317)
[ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.InterTypeFieldDeclaration.generateCode(InterTypeFieldDeclaration.java:307)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:775)
[ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.AspectDeclaration.generateCode(AspectDeclaration.java:297)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:873)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:403)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:983)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:604)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:505)
[ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:456)
[ERROR] 	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1101)
[ERROR] 	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:275)
[ERROR] 	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:188)
[ERROR] 	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:103)
[ERROR] 	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:47)
[ERROR] 	at org.aspectj.tools.ajc.Main.run(Main.java:385)
[ERROR] 	at org.aspectj.tools.ajc.Main.runMain(Main.java:274)
[ERROR] 	at org.codehaus.mojo.aspectj.AbstractAjcCompiler.execute(AbstractAjcCompiler.java:568)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at com.gradle.maven.cache.extension.d.n.a(SourceFile:53)
[ERROR] 	at com.gradle.maven.cache.extension.d.d.a(SourceFile:27)
[ERROR] 	at com.gradle.maven.cache.extension.d.q.a(SourceFile:23)
[ERROR] 	at com.gradle.maven.cache.extension.d.j.a(SourceFile:28)
[ERROR] 	at com.gradle.maven.cache.extension.d.p.a(SourceFile:27)
[ERROR] 	at com.gradle.maven.cache.extension.d.b.c(SourceFile:118)
[ERROR] 	at com.gradle.maven.cache.extension.d.b.a(SourceFile:62)
[ERROR] 	at com.gradle.maven.cache.extension.d.g.a(SourceFile:27)
[ERROR] 	at com.gradle.maven.cache.extension.d.a.a(SourceFile:46)
[ERROR] 	at com.gradle.maven.cache.extension.d.o.a(SourceFile:18)
[ERROR] 	at com.gradle.maven.cache.extension.d.a.a(SourceFile:46)
[ERROR] 	at com.gradle.maven.cache.extension.d.c.a(SourceFile:26)
[ERROR] 	at com.gradle.maven.cache.extension.d.h$1.run(SourceFile:35)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(SourceFile:29)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(SourceFile:26)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(SourceFile:66)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(SourceFile:59)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(SourceFile:166)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(SourceFile:59)
[ERROR] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(SourceFile:47)
[ERROR] 	at com.gradle.maven.cache.extension.d.h.a(SourceFile:31)
[ERROR] 	at com.gradle.maven.cache.extension.d.m.a(SourceFile:82)
[ERROR] 	at com.gradle.maven.cache.extension.h.b.lambda$createProxy$0(SourceFile:76)
[ERROR] 	at jdk.proxy11/jdk.proxy11.$Proxy93.execute(Unknown Source)
[ERROR] 	at com.gradle.maven.scan.extension.internal.d.b.executeMojo(SourceFile:116)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
```

I noticed the Java 1.1 > 1.7 support dropping in the release note and https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2624, and I guess it's linked in some way, but we are targeting and building with Java 17.

I also attached the [ajcore](https://github.com/user-attachments/files/19337415/ajcore.20250319.093326.536.txt) report file.

The file mentioned in the error is https://github.com/xwiki/xwiki-platform/blob/14b5462c47ff7b776de3544bcb4dedfaf6fb30c8/xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/src/main/aspect/com/xpn/xwiki/doc/XWikiDocumentCompatibilityAspect.aj, and it's patching https://github.com/xwiki/xwiki-platform/blob/14b5462c47ff7b776de3544bcb4dedfaf6fb30c8/xwiki-platform-core/xwiki-platform-oldcore/src/main/java/com/xpn/xwiki/doc/XWikiDocument.java.

To reproduce:
* clone https://github.com/xwiki/xwiki-platform
* add the XWiki snapshot maven repository to settings.xml as suggested in https://dev.xwiki.org/xwiki/bin/view/Community/Building/#HInstallingMaven
* go to `xwiki-platform-core/xwiki-platform-legacy/xwiki-platform-legacy-oldcore/`
* add `<aspectj.version>1.9.23</aspectj.version>` to the pom.xml `<properties>` (since I put back 1.9.22.1 in the parent)
* build (`mvn clean install` for example)

**Comment by kriegaex** [comment]
Your instructions are not working. First, I had to activate long file name support in Git for Windows. Next, I had to specify `-P xwiki` to activate the profile, then I got a Develocity error and had to deactivate the build extensions and finally, a parent POM was not found. Please either refine the build instructions or - much preferred - condense the problem into a minimal reproducer without all the XWiki stuff around.

**Comment by tmortagne** [comment]
Thanks a lot for spending time on it.

> I had to activate long file name support in Git for Windows

Sorry, I don't have that much experience with Windows on this, so I don't always think about indicating special instructions for it.

>  I had to specify -P xwiki

If you are talking about the profile indicated in the suggested settings.xml file, it's also activated by default in that same file so it should not be needed.

> I got a Develocity error

That one is strange, maybe there is a problem with Develocity on Windows (we don't have a Windows agent in our CI so we don't always catch problems like this until a Windows dev, which are rare in the XWiki community apparently, try it).

> a parent POM was not found

If by that you mean that Maven told you it could not find the parent pom, that's pretty much all the suggested repositories to add in the setting.xml are for (in this specific case https://nexus-snapshots.xwiki.org/repository/snapshots/). So I guess it means they are not taken into account in your case for some reason.

Anyway, thanks again for taking the time, I will try to find some time today trying to reproduce the same error in a simpler use case, at least in terms of setup.

**Comment by aclement** [comment]
Hey @tmortagne - i'm not totally surprised to see the issue, there are some different behaviours in the Eclipse compiler we've picked up for Java23 - I go into more detail in #328 - I think this is the same thing for a different code generation path rather to intertype fields.

**Comment by kriegaex** [comment]
> If you are talking about the profile indicated in the suggested settings.xml file, it's also activated by default in that same file so it should not be needed. 

Thanks for the hint, I had forgotten to do that. Why I cannot activate it manually, I am not sure. But
```xml
  <activeProfiles>
    <!-- ... -->
    <activeProfile>xwiki</activeProfile>
  </activeProfiles>
```
did the trick. I can now build and reproduce the problem. @aclement, the command I used to speed up things was `mvn -DskipTests -Denforcer.skip clean compile`, because there was also one failing test on Windows (for phases later than `compile`, e.g. `package` or `install`).

**Edit:** Duh, one space too many in the command line from my previous post. It is not `-P xwiki`, but `-Pxwiki`, i.e. even without `<activeProfile>xwiki</activeProfile>` the following command line works:

```bash
mvn -Pxwiki -DskipTests -Denforcer.skip clean compile
```

At first, there were so many build errors that I had not even considered having made a Maven CLI syntax error.

**Comment by tmortagne** [comment]
In case it's still useful, here is a much simpler Maven module ([reproduction.zip](https://github.com/user-attachments/files/19387213/reproduction.zip)) which produce the same error (hoping I did not remove too much, and it's not actually erroring for a different reason).

A simple `mvn clean package` should do (the needed maven repository is in the pom this time and there is no fancy plugin creating noise anymore).

**Comment by aclement** [comment]
That's great @tmortagne - from your sample I distilled a small standalone repro case:

```
privileged public aspect A {
    public static final String B.s = C.f.toString();
}

class B { }

class C {
 public static final C f = new C();
}
```

`ajc -17 A.aj` then breaks with the same stack trace.

**Comment by aclement** [comment]
Fixed. Added a number of tests for the version of the problem here and some closely related variants. Also built a snapshot build and XWiki seemed to be OK with it (thanks @kriegaex for the short hand to running a build).

**Comment by tmortagne** [comment]
Thanks for the quick fix @aclement and @kriegaex !

**Comment by kriegaex** [comment]
You are welcome, @tmortagne. But other than guiding you a bit to make the problem reproducible and trying it on my box, I did not do anything. Andy did all the real work, the credit is his. My situation is still the same: no sponsor, so I am staying away from committing code for the time being.

**Comment by stefandotti** [comment]
unfortunate the error this persists with 1.9.24: (i will try to create a minimal sample)

```text
2025-04-14 09:24:51.087  [ERROR] /tmp/workspace/feature_renovate_version.aspectj/risiko-common/src/main/aspect/RMRiskInformationCache.aj:0::0 Internal compiler error: java.lang.AssertionError: Attempt to push null on operand stack! at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:58)
2025-04-14 09:24:51.088  [ERROR] abort ABORT -- (AssertionError) Attempt to push null on operand stack!
2025-04-14 09:24:51.088  [ERROR] Attempt to push null on operand stack!
2025-04-14 09:24:51.088  [ERROR] java.lang.AssertionError: Attempt to push null on operand stack!
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:58)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:84)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload_2(CodeStream.java:366)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.CodeStream.load(CodeStream.java:6282)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.AdviceDeclaration.generateProceedMethod(AdviceDeclaration.java:240)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.AdviceDeclaration.generateCode(AdviceDeclaration.java:284)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:777)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.AspectDeclaration.generateCode(AspectDeclaration.java:297)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:875)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:403)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:837)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:458)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:359)
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:310)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1102)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:276)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:189)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:103)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:47)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.tools.ajc.Main.run(Main.java:385)
2025-04-14 09:24:51.089  [ERROR] 	at org.aspectj.tools.ajc.Main.runMain(Main.java:274)
2025-04-14 09:24:51.089  [ERROR] 	at org.codehaus.mojo.aspectj.AbstractAjcCompiler.execute(AbstractAjcCompiler.java:568)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:210)
2025-04-14 09:24:51.089  [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:195)
2025-04-14 09:24:51.090  [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2025-04-14 09:24:51.090  [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2025-04-14 09:24:51.090  [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2025-04-14 09:24:51.090  [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-04-14 09:24:51.090  [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2025-04-14 09:24:51.090  [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:840)
2025-04-14 09:24:51.090  [ERROR] -> [Help 1]
```

**Comment by aclement** [comment]
Hmm, looks like a different one to the original (original was intertype field declaration related). 

This one being related to the proceed method code generation:

```
2025-04-14 09:24:51.088  [ERROR] 	at org.aspectj.ajdt.internal.compiler.ast.AdviceDeclaration.generateProceedMethod(AdviceDeclaration.java:240)
```

I think I'll spin it off into a new issue. Same core problem though I suspect, needing to tell the code generator more about the variables involved. Thanks for anything you can do around a minimal test case, I don't like fixing these without a testcase. As your problem surfaces a number of these, I might get you to try an RC of the next build to verify we've caught them all (well at least all of yours!)

**Comment by stefandotti** [comment]
A minimal sample: [aspect-test.zip](https://github.com/user-attachments/files/19758507/aspect-test.zip)

produces this: [ERROR] Internal compiler error: java.lang.AssertionError: Attempt to push null on operand stack! at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:58)
	C:\Entwicklung\git\aspect-test\src\main\aspect\RMRiskInformationCache.aj:0

**Comment by aclement** [comment]
Perfect @stefandotti (thank you) that helped me distill this:

```
public aspect X {
  pointcut p(long l): call(* F.m(..)) && args(l);
  Object around (long id): p(id) { return null; }
}

class F {
    public void m(long r) {}
}
```

`ajc -17 X.aj`

```
java.lang.AssertionError: Attempt to push null on operand stack!
	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:58)
	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.OperandStack.push(OperandStack.java:84)
	at org.aspectj.org.eclipse.jdt.internal.compiler.codegen.CodeStream.aload(CodeStream.java:305)
	at org.aspectj.ajdt.internal.compiler.ast.AdviceDeclaration.generateProceedMethod(AdviceDeclaration.java:227)
```

All my attempts were just finding other issues! (e.g. #336  ). I think it is the `long` that is blowing things up (probably due to being double slot variable like `double`). Interestingly I was trying the xwiki build instructions above with 1.9.24 and it didn't fail with this problem but I'll admit I haven't done a pull in a while.

**Comment by aclement** [comment]
Created #337 to cover fixing this in the next release

**Comment by tmortagne** [comment]
>  Interestingly I was trying the xwiki build instructions above with 1.9.24 and it didn't fail with this problem but I'll admit I haven't done a pull in a while.

I don't think @stefandotti's use case is related to XWiki :)
